test: failing "highlights forward search / for long line" #2333
Problem:
ci failure:

    Test highlights
      forward search / for long line:
    Error: Extension 'asvetliakov.vscode-neovim' CANNOT use API proposal: nativeWindowHandle.
    Its package.json#enabledApiProposals-property declares: [] but NOT nativeWindowHandle.
     The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api asvetliakov.vscode-neovim
     at L (file:///d:/a/…js:113:16650)
     at Object.get nativeHandle [as nativeHandle] (file:///d:/a/…js:157:50586)
     at Function.assign (<anonymous>)
     at d:\a\vscode-neovim\vscode-neovim\src\test\integ\highlights.test.ts:97:25

Solution:
Instead of overwriting `vscode.window` in a blunt way, overwrite only
the 2 properties that we actually care about.

fix #2329